"""start version of store

Revision ID: a41b52ee2c3d
Revises: 
Create Date: 2023-08-23 20:49:49.900997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41b52ee2c3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
